travis:
  secure:
    BINSTAR_TOKEN: DI+csaEDwz4qs+HN+qhq1NLIKnWMhtBv9+zZi9IXYxt2zkfZ7YMdD3FBy7rUxLX2FwKC++4FNXPvdtPpTAvDQTMBeVf9K2xOPs3PDAVK3vAB28hdoF9+xViTDnXii/l4Mi19lsNZp+zNbZr1HuAMt9rMHNOuWh0i1xS3oUtuqPFlkt1EzU35u0/LTiBc88FVzt+yLI3n1mMnqd0AaaWOBlsIjHtSsj3864mEoPs1nFkcyNT/sS0oKpC5NYO8CDLxGaBQcbaiehRPWkZCheOQBlA01ykIaeusrC/R8jFk2Q4UD3QvbihQjYhk3tdu4Mx5CsQunv6tbEOPTfjtdm1AQwF2CJgyamE/cy77IRbcCiJzC4NgK5OTirDWPV2LsGkksa4J4D27CZEC8QxOzKUKEGOBgoHCucKRqHZ2MhFZt9A4eiWYOqRyUZg+WjmqlsQDAM8SKACYwBHh0duW/C3UhqNW5yMZgo9N+zn6Wbk9Hd3NWWdg4gDyhXDows8usdKCX+jOhceTd4mnMtHUDLB4R7tQ65q7nCOsXqUXr9MdYOOIEIh1OB8VekV1Ya2kh+pvll/JeGkJueVaD4efC8i5d1k7IWU3dxLPLHZ+8T5YD9xmMXAghzMQrsB5kwHHC5vcCcosjD7Xv0966WzJ2jmjB8jkfvCcoAwsSU+pt+S6zI4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
